// backups/src/components/ExperimentalVideoPlayer.vue
<template>
  <div class="experimental-video-player">
    <video
      ref="videoPlayer"
      :src="currentVideo?.src"
      @ended="handleVideoEnd"
      v-show="isExperimentRunning"
    ></video>
    
    <div v-if="!isExperimentRunning && !isExperimentComplete" class="controls">
      <el-button @click="startExperiment" type="primary">开始实验</el-button>
    </div>
    
    <div v-if="isExperimentRunning" class="controls">
      <el-button @click="exitExperiment" type="danger">退出实验</el-button>
    </div>
    
    <el-dialog v-model="showUploadDialog" title="上传脑电数据" width="30%" :close-on-click-modal="false">
      <el-upload
        class="upload-demo"
        drag
        action="/api/upload-eeg"
        :on-success="handleUploadSuccess"
        :on-error="handleUploadError"
      >
        <i class="el-icon-upload"></i>
        <div class="el-upload__text">将文件拖到此处，或<em>点击上传</em></div>
      </el-upload>
    </el-dialog>
    
    <el-dialog v-model="showResultDialog" title="实验结果" width="50%" :close-on-click-modal="false">
      <pre>{{ experimentResult }}</pre>
      <template #footer>
        <span class="dialog-footer">
          <el-button type="primary" @click="finishExperiment">完成</el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { ElButton, ElDialog, ElUpload } from 'element-plus'

const videoPlayer = ref(null)
const currentVideo = ref(null)
const isExperimentRunning = ref(false)
const isExperimentComplete = ref(false)
const showUploadDialog = ref(false)
const showResultDialog = ref(false)
const experimentResult = ref('')

const videos = ref([])
const videoTimings = ref([])
const currentVideoIndex = ref(0)

let waitTimer = null

onMounted(() => {
  fetchVideos()
})

onUnmounted(() => {
  clearTimeout(waitTimer)
})

const fetchVideos = async () => {
  try {
    const response = await fetch('/api/videos/experimental')
    videos.value = await response.json()
  } catch (error) {
    console.error('Error fetching videos:', error)
  }
}

const startExperiment = () => {
  isExperimentRunning.value = true
  currentVideoIndex.value = 0
  videoTimings.value = []
  playNextVideo()
}

const exitExperiment = () => {
  isExperimentRunning.value = false
  videoPlayer.value.pause()
  clearTimeout(waitTimer)
  // Data is discarded when exiting
}

const playNextVideo = () => {
  if (currentVideoIndex.value < 5) {
    currentVideo.value = videos.value[currentVideoIndex.value]
    const startTime = new Date().toISOString()
    videoTimings.value.push({ videoId: currentVideo.value.id, startTime })
    videoPlayer.value.play()
  } else {
    isExperimentRunning.value = false
    isExperimentComplete.value = true
    showUploadDialog.value = true
  }
}

const handleVideoEnd = () => {
  const endTime = new Date().toISOString()
  videoTimings.value[currentVideoIndex.value].endTime = endTime
  currentVideoIndex.value++
  
  waitTimer = setTimeout(() => {
    playNextVideo()
  }, 60000) // Wait for 1 minute
}

const handleUploadSuccess = async (response) => {
  showUploadDialog.value = false
  try {
    const result = await sendExperimentData(response.eegFileUrl)
    experimentResult.value = JSON.stringify(result, null, 2)
    showResultDialog.value = true
  } catch (error) {
    console.error('Error processing experiment data:', error)
  }
}

const handleUploadError = () => {
  console.error('Error uploading EEG file')
}

const sendExperimentData = async (eegFileUrl) => {
  const response = await fetch('/api/process-experiment', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      videoTimings: videoTimings.value,
      eegFileUrl,
    }),
  })
  return await response.json()
}

const finishExperiment = () => {
  showResultDialog.value = false
  isExperimentComplete.value = false
  // Reset the experiment state
}
</script>

<style scoped>
.experimental-video-player {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
}

video {
  max-width: 100%;
  max-height: 70vh;
}

.controls {
  margin-top: 20px;
}
</style>

// components/experiments/ExperimentalVideoPlayer.tsx
'use client';

import React, { useState, useRef, useEffect } from 'react';
import { Button, Dialog, Upload } from '@/components/ui';

interface Video {
  id: string;
  title: string;
  src: string;
}

export default function ExperimentalVideoPlayer() {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [videos, setVideos] = useState<Video[]>([]);
  const [currentVideoIndex, setCurrentVideoIndex] = useState(0);
  const [isExperimentRunning, setIsExperimentRunning] = useState(false);
  const [isExperimentComplete, setIsExperimentComplete] = useState(false);
  const [showUploadDialog, setShowUploadDialog] = useState(false);
  const [showResultDialog, setShowResultDialog] = useState(false);
  const [experimentResult, setExperimentResult] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    fetchVideos();
  }, []);

  const fetchVideos = async () => {
    try {
      const response = await fetch('/api/experiment-videos');
      if (response.ok) {
        const data = await response.json();
        setVideos(data);
      }
    } catch (error) {
      console.error('Error fetching videos:', error);
    }
  };

  const startExperiment = () => {
    setIsExperimentRunning(true);
    playVideo();
  };

  const exitExperiment = () => {
    setIsExperimentRunning(false);
    if (videoRef.current) {
      videoRef.current.pause();
    }
  };

  const playVideo = () => {
    if (videoRef.current) {
      videoRef.current.play();
    }
  };

  const playNextVideo = () => {
    if (currentVideoIndex < videos.length - 1) {
      setCurrentVideoIndex(prev => prev + 1);
      setTimeout(() => playVideo(), 100);
    } else {
      setShowUploadDialog(true);
    }
  };

  const handleVideoEnd = () => {
    playNextVideo();
  };

  const handleUploadSuccess = async (info: any) => {
    setShowUploadDialog(false);
    setIsLoading(true);
    
    try {
      await sendExperimentData(info.response.url);
    } catch (error) {
      console.error('Error sending experiment data:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleUploadError = () => {
    console.error('Upload failed');
  };

  const sendExperimentData = async (eegFileUrl: string) => {
    try {
      const response = await fetch('/api/process-experiment', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          videos: videos.map(v => v.id),
          eegFile: eegFileUrl
        }),
      });
      
      if (response.ok) {
        const result = await response.json();
        setExperimentResult(JSON.stringify(result, null, 2));
        setShowResultDialog(true);
      }
    } catch (error) {
      console.error('Error processing experiment:', error);
    }
  };

  const finishExperiment = () => {
    setShowResultDialog(false);
    setIsExperimentRunning(false);
    setIsExperimentComplete(true);
  };

  return (
    <div className="flex flex-col items-center space-y-4">
      {videos.length > 0 && (
        <video
          ref={videoRef}
          src={videos[currentVideoIndex]?.src}
          className={`w-full max-w-3xl aspect-video ${!isExperimentRunning ? 'hidden' : ''}`}
          onEnded={handleVideoEnd}
        />
      )}
      
      {!isExperimentRunning && !isExperimentComplete && (
        <div className="controls">
          <Button onClick={startExperiment} variant="default">开始实验</Button>
        </div>
      )}
      
      {isExperimentRunning && (
        <div className="controls">
          <Button onClick={exitExperiment} variant="destructive">退出实验</Button>
        </div>
      )}
      
      {showUploadDialog && (
        <Dialog open={showUploadDialog} onOpenChange={setShowUploadDialog}>
          <div className="p-6">
            <h2 className="text-lg font-bold mb-4">上传脑电数据</h2>
            <Upload
              action="/api/upload-eeg"
              onSuccess={handleUploadSuccess}
              onError={handleUploadError}
            />
          </div>
        </Dialog>
      )}
      
      {showResultDialog && (
        <Dialog open={showResultDialog} onOpenChange={setShowResultDialog}>
          <div className="p-6">
            <h2 className="text-lg font-bold mb-4">实验结果</h2>
            <pre className="bg-gray-100 p-4 rounded overflow-auto max-h-96">
              {experimentResult}
            </pre>
            <div className="mt-4 flex justify-end">
              <Button onClick={finishExperiment}>完成</Button>
            </div>
          </div>
        </Dialog>
      )}
    </div>
  );
}
